module.exports = require('./datatables.js');
require('./datatables.css');
require('datatables.net-buttons');
require('./extensions/buttons.colVis.js');
require('./extensions/colReorder.js');
require('./extensions/colReorder.css');
require('./extensions/fixedHeader.js');
require('./extensions/fixedHeader.css');
require('./extensions/responsive.js');
require('./extensions/responsive.css');
require('./extensions/scroller.js');
require('./extensions/scroller.css');
require('./datatables-custom.styl');
